### PR TITLE
Fix sleep time overflow

### LINKED ISSUE #220: sleep function - overflow
I'm working on an ATmega1284p with the RN2483A. When putting the device to sleep using the library the module does not go to sleep.
I'm using ttn.sleep(4294967295); where 4294967295 is the maximum value defined in the documentation. The result "sys sleep -1" is send to the RN2483, which results in nothing. 
If I use 2147483647 or less it works and sends "sys sleep 2147483647" and i can see the power usage go down. 
I guess somewhere there is a overflow in the library but I have not been able to spot where.

### PR DESCRIPTION
**Pull request by johanstokking**
Closes #220

### CODE REVIEW

File: src/TheThingsNetwork.cpp [hunk 1]
```diff
@@ -945,7 +945,7 @@ bool TheThingsNetwork::sendPayload(uint8_t mode, uint8_t port, uint8_t *payload,
 
 void TheThingsNetwork::sleep(uint32_t mseconds)
 {
-  if (mseconds < 100 || mseconds >= 4294967296)
```
Comment (jpmeijers) [inline src/TheThingsNetwork.cpp]: Actually this check doesn't make sense. An unsigned 32 bit parameter can never be >=2^32. So doing this check doesn't have any effect.

Comment (johanstokking) [inline src/TheThingsNetwork.cpp]: That's why the line is red 😉
